#!/usr/bin/env python3
"""
Find pa.city values in production that aren't in the admin's
city→borough mapping.

The locations admin's heatmap and borough-breakdown rely on
`_get_admin_city_to_borough()` to route every `pa.city` value to one
of the five NYC boroughs (or "Other"). If a real NYC neighborhood
appears in `pa.city` but isn't in the mapping, it silently falls to
"Other" — under-counting that borough in the visible heatmap.

This script identifies those silent gaps. It has two modes:

    # Mode 1: print the diagnostic SQL with the live mapping baked in.
    # Pipe to psql or paste into your DB tool of choice.
    python tools/check_city_coverage.py --print-sql
    python tools/check_city_coverage.py --print-sql | psql $DATABASE_URL

    # Mode 2: run the diagnostic against the configured database
    # (uses the same DATABASE_URL the rest of the app reads from).
    python tools/check_city_coverage.py --run

Output of mode 2 is a sorted table:

    location_count | pa.city               | suggested_borough_or_other
    --------------:|-----------------------|---------------------------
              123  | "Some Real Neighborhood" | NEEDS REVIEW
                7  | "Yonkers"             | non-NYC (correctly Other)
                3  | "4600 E 48th Ave"     | data-quality bug (correctly Other)

Rows marked "NEEDS REVIEW" are the candidates: real-looking
neighborhood names with non-trivial location counts that aren't in
the mapping. Eyeball each, decide whether it's a NYC borough that
needs adding to `_ADMIN_EXTRA_CITY_ALIASES`, then re-run.

Output is sorted by location_count DESC so the highest-impact gaps
appear first.

The "suggested" column is a heuristic (length, common-word checks).
It only exists to help the human triage; it doesn't auto-map anything.

Exit codes:
    0  — ran successfully (mode 2)
    1  — DB connection failed or query errored (mode 2)
    2  — script invoked with no mode flag
"""
from __future__ import annotations

import argparse
import os
import sys


def _load_mapping() -> dict[str, str]:
    """Import the live admin mapping. Done here rather than at
    module top so `--print-sql` doesn't require a working backend
    install — but it does mean ImportError surfaces at run-time, not
    import-time. Acceptable trade for a dev tool.
    """
    # Make `backend` importable from the repo root.
    here = os.path.dirname(os.path.abspath(__file__))
    backend = os.path.join(os.path.dirname(here), "backend")
    if backend not in sys.path:
        sys.path.insert(0, backend)

    from app.services.locations_admin.aggregations import (
        _get_admin_city_to_borough,
    )
    return _get_admin_city_to_borough()


def _values_block(mapping: dict[str, str]) -> str:
    """Render the mapping as a VALUES clause for the CTE.

    Sorted for deterministic diff-able output. Single-quotes
    escaped defensively even though current data has none.
    """
    rows: list[str] = []
    for city in sorted(mapping.keys()):
        borough = mapping[city]
        safe_city = city.replace("'", "''")
        safe_borough = borough.replace("'", "''")
        rows.append(f"    ('{safe_city}', '{safe_borough}')")
    return ",\n".join(rows)


def generate_sql(mapping: dict[str, str]) -> str:
    """Build the full diagnostic SQL with the mapping embedded."""
    values = _values_block(mapping)
    return f"""\
-- ═══════════════════════════════════════════════════════════════
-- City coverage diagnostic — find pa.city values that aren't in
-- the admin's city→borough mapping.
--
-- Generated by tools/check_city_coverage.py from the live mapping
-- in backend/app/services/locations_admin/aggregations.py.
-- Mapping size at generation time: {len(mapping)} entries.
--
-- Re-run the tool any time you change _ADMIN_EXTRA_CITY_ALIASES.
-- ═══════════════════════════════════════════════════════════════

WITH mapped(city_lower, borough) AS (
    VALUES
{values}
),
distinct_cities AS (
    SELECT
        pa.city                          AS raw_city,
        LOWER(TRIM(pa.city))             AS city_lower,
        COUNT(DISTINCT pa.location_id)   AS location_count
    FROM physical_addresses pa
    WHERE pa.city IS NOT NULL
      AND TRIM(pa.city) <> ''
    GROUP BY pa.city
)
SELECT
    dc.raw_city,
    dc.location_count,
    -- Heuristic: a value is "likely NYC" if it's short (< 30 chars),
    -- doesn't look like a street address (no leading digits), and
    -- isn't an obvious non-NYC city. This is a triage hint only.
    CASE
        WHEN dc.raw_city ~ '^[0-9]'
            THEN 'data-quality (address in city field)'
        WHEN LENGTH(dc.raw_city) > 35
            THEN 'data-quality (too long)'
        WHEN LOWER(TRIM(dc.raw_city)) IN (
            -- New Jersey
            'jersey city', 'newark', 'elizabeth', 'elizabethport',
            'union city', 'west new york', 'secaucus', 'bayonne',
            'hoboken', 'passaic', 'paterson', 'hackensack',
            'monroe township',
            -- Westchester / Hudson Valley
            'yonkers', 'mount vernon', 'new rochelle', 'white plains',
            'scarsdale', 'eastchester', 'newburgh', 'kingston',
            'middletown', 'poughkeepsie',
            -- Long Island (Nassau + Suffolk)
            'mineola', 'hempstead', 'great neck', 'long beach',
            'oceanside', 'massapequa park', 'bethpage', 'melville',
            'farmingdale', 'huntington', 'hicksville',
            -- "Long Island" without qualifier — geographically
            -- includes Queens/Brooklyn but colloquially means
            -- Nassau/Suffolk. Conservative: don't auto-map.
            'long island',
            -- Upstate NY
            'albany', 'syracuse', 'ithaca', 'buffalo',
            -- Out of state
            'miami', 'washington', 'bethesda', 'carmel', 'harrison',
            'denver', 'sanger',
            -- Probable typo / unknown — Gardena (CA) misspelled?
            'gardenia'
            )
            THEN 'non-NYC (correctly Other)'
        ELSE 'NEEDS REVIEW — possibly missing NYC neighborhood'
    END AS triage_hint
FROM distinct_cities dc
LEFT JOIN mapped m ON m.city_lower = dc.city_lower
WHERE m.city_lower IS NULL
ORDER BY
    -- "NEEDS REVIEW" first (highest priority), then by count DESC
    CASE
        WHEN dc.raw_city ~ '^[0-9]' THEN 2
        WHEN LENGTH(dc.raw_city) > 35 THEN 2
        ELSE 0
    END,
    dc.location_count DESC,
    dc.raw_city;
"""


def _run_against_db(sql: str) -> int:
    """Execute the diagnostic SQL via the same DB plumbing the app
    uses. Prints a tab-separated report.

    Returns the process exit code (0 success, 1 error).
    """
    # _execute_sql is the same helper the production aggregations
    # use. Avoids re-implementing connection/timeout/pool logic.
    try:
        from app.rag.query_executor import _execute_sql
    except ImportError as e:
        print(f"ERROR: backend not importable: {e}", file=sys.stderr)
        print(
            "Run from the repo root with PYTHONPATH=backend, or use "
            "--print-sql and run the SQL externally.",
            file=sys.stderr,
        )
        return 1

    if not os.getenv("DATABASE_URL"):
        print("ERROR: DATABASE_URL not set", file=sys.stderr)
        print(
            "Set DATABASE_URL in your environment, or use --print-sql "
            "and run the SQL externally.",
            file=sys.stderr,
        )
        return 1

    try:
        rows = _execute_sql(sql, {})
    except Exception as e:  # pragma: no cover — depends on live DB
        print(f"ERROR: query failed: {e}", file=sys.stderr)
        return 1

    if not rows:
        print(
            "✅ No unmapped pa.city values found. Every value in "
            "physical_addresses.city is currently routed to a borough "
            "(NYC or Other) by the live mapping.",
            file=sys.stderr,
        )
        return 0

    needs_review = [r for r in rows if "NEEDS REVIEW" in (r.get("triage_hint") or "")]
    non_nyc = [r for r in rows if "non-NYC" in (r.get("triage_hint") or "")]
    junk = [r for r in rows if "data-quality" in (r.get("triage_hint") or "")]

    print(
        f"Unmapped pa.city values: {len(rows)} total | "
        f"{len(needs_review)} need review | "
        f"{len(non_nyc)} non-NYC (correctly Other) | "
        f"{len(junk)} data-quality\n",
        file=sys.stderr,
    )

    # Headers
    print("location_count\traw_city\ttriage_hint")
    # NEEDS REVIEW section first.
    for label, group in (
        ("NEEDS REVIEW", needs_review),
        ("non-NYC", non_nyc),
        ("data-quality", junk),
    ):
        if not group:
            continue
        print(f"\n# --- {label} ({len(group)}) ---", file=sys.stderr)
        for r in group:
            print(
                f"{r.get('location_count')}\t"
                f"{r.get('raw_city')!r}\t"
                f"{r.get('triage_hint')}"
            )

    if needs_review:
        print(
            f"\n→ {len(needs_review)} candidate(s) for adding to "
            f"_ADMIN_EXTRA_CITY_ALIASES. Eyeball each, confirm it's a "
            f"real NYC neighborhood, then add lowercase entries to the "
            f"dict and re-run.",
            file=sys.stderr,
        )
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    group = parser.add_mutually_exclusive_group(required=False)
    group.add_argument(
        "--print-sql",
        action="store_true",
        help="Print the diagnostic SQL to stdout (with the live mapping baked in)",
    )
    group.add_argument(
        "--run",
        action="store_true",
        help="Run the diagnostic against DATABASE_URL and print the report",
    )
    args = parser.parse_args(argv)

    mapping = _load_mapping()
    sql = generate_sql(mapping)

    if args.print_sql:
        print(sql)
        return 0
    if args.run:
        return _run_against_db(sql)

    parser.print_help()
    return 2


if __name__ == "__main__":
    sys.exit(main())
